### ISSUE TITLE
service not creating CNAMEs at startup

### ISSUE THREAD

**Issue by auspex** [hardillb/traefik-avahi-helper#13]
I have a very simple stack, consisting solely of `traefik` and `traefik-avahi-helper`.

```yaml
version: "3"
services:
  avahi:
    image: hardillb/traefik-avahi-helper
    container_name: avahi
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket

  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    command: --api.insecure=true --providers.docker
    ports:
      - 80:80
      - 443:443
    labels:
      - traefik.http.routers.traefik.rule=Host(`traefik.local`)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```
On `docker-compose up -d`, the avahi log always shows:
```
> traefik-avahi-helper@1.0.1 start
> node index.js
[]
starting cname.py
INFO: All CNAMEs published
```
and I can't resolve traefik.local, but if I make any change to the traefik service:
```
-      - 80:80
+      - 0.0.0.0:80:80
```
and `docker-compose up -d`, again, `traefik.local` is published!
```
Removing [ 'traefik.local' ]
restarting cname.py with /usr/src/app/cnames
starting cname.py
INFO: All CNAMEs published
Adding [ 'traefik.local' ]
restarting cname.py with /usr/src/app/cnames
starting cname.py
INFO: All CNAMEs published
```
It has nothing to do with the change from TCPv4+TCPv6 to TCPv4, as if I `docker-compose down;docker-compose up -d` without further changes, the CNAME will once again not be published.

I've tried making traefik `depends_on` traefik-avahi-helper, and vice versa.
I've tried stopping the  traefik-avahi-helper container and restarting it. Nothing seems to make a difference.

What am I missing?
