### ISSUE TITLE
DOCS: Add compose version

### ISSUE THREAD

**Issue by tanishqmanuja** [hardillb/traefik-avahi-helper#16]
I have tested this, works just fine. You can add compose version to the readme making it easy for user to copy 🚀

```
services:
  traefik-avahi-helper:
    container_name: "traefik-avahi-helper"
    image: hardillb/traefik-avahi-helper
    security_opt:
      - apparmor:unconfined
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
    restart: unless-stopped
```
