### ISSUE TITLE
cnames are not promoted

### ISSUE THREAD

**Issue by bikaro** [hardillb/traefik-avahi-helper#5]
I don't  get any errors, the container is running fine. It also extract the correct domains from the labels but in the end, the cnames are not promoted by avahi to other machines neither the own. The container is running wthout problems.

log from container:
```
> traefik-avahi-helper@1.0.1 start /usr/src/app
> node index.js

[ 'syncthing.mymachine.local', 'traefik.mymachine.local', 'git.mymachine.local' ]
starting cname.py
INFO: All CNAMEs published
```

My docker-compose file:
```yml
version: "3.3"

services:

  traefik-avahi-helper:
    image: hardillb/traefik-avahi-helper
    container_name: "traefik-avahi-helper"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/run/dbus/system_bus_socket:/run/dbus/system_bus_socket"
    restart: always
```
I am running avahi-daemon 0.7 on a raspberry pi 4 with rabian.
Are any other libraries required?

The same results on my laptop with ubuntu 20.04.1,  avahi-daemon 0.7. Here the container runs with privileged keyword.
